<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterFilmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('character_films')->truncate();
        foreach (self::$character_films as $character_film) {
            DB::table('character_films')->insert([
                'id_character' => $character_film['id_character'],
                'id_film' => $character_film['id_film'],
            ]);
        }
    }

    private static $character_films = array(
        array('id_character' => '1','id_film' => '4'),
        array('id_character' => '1','id_film' => '5'),
        array('id_character' => '1','id_film' => '6'),
        array('id_character' => '2','id_film' => '1'),
        array('id_character' => '2','id_film' => '2'),
        array('id_character' => '2','id_film' => '3'),
        array('id_character' => '2','id_film' => '4'),
        array('id_character' => '2','id_film' => '5'),
        array('id_character' => '2','id_film' => '6'),
        array('id_character' => '3','id_film' => '1'),
        array('id_character' => '3','id_film' => '2'),
        array('id_character' => '3','id_film' => '3'),
        array('id_character' => '3','id_film' => '4'),
        array('id_character' => '3','id_film' => '5'),
        array('id_character' => '3','id_film' => '6'),
        array('id_character' => '4','id_film' => '3'),
        array('id_character' => '4','id_film' => '4'),
        array('id_character' => '4','id_film' => '5'),
        array('id_character' => '4','id_film' => '6'),
        array('id_character' => '5','id_film' => '4'),
        array('id_character' => '5','id_film' => '5'),
        array('id_character' => '5','id_film' => '6'),
        array('id_character' => '6','id_film' => '2'),
        array('id_character' => '6','id_film' => '3'),
        array('id_character' => '6','id_film' => '4'),
        array('id_character' => '7','id_film' => '2'),
        array('id_character' => '7','id_film' => '3'),
        array('id_character' => '7','id_film' => '4'),
        array('id_character' => '8','id_film' => '4'),
        array('id_character' => '9','id_film' => '4'),
        array('id_character' => '10','id_film' => '1'),
        array('id_character' => '10','id_film' => '2'),
        array('id_character' => '10','id_film' => '3'),
        array('id_character' => '10','id_film' => '4'),
        array('id_character' => '11','id_film' => '1'),
        array('id_character' => '11','id_film' => '2'),
        array('id_character' => '11','id_film' => '3'),
        array('id_character' => '12','id_film' => '4'),
        array('id_character' => '13','id_film' => '3'),
        array('id_character' => '13','id_film' => '4'),
        array('id_character' => '13','id_film' => '5'),
        array('id_character' => '13','id_film' => '6'),
        array('id_character' => '14','id_film' => '4'),
        array('id_character' => '14','id_film' => '5'),
        array('id_character' => '14','id_film' => '6'),
        array('id_character' => '15','id_film' => '4'),
        array('id_character' => '16','id_film' => '6'),
        array('id_character' => '18','id_film' => '4'),
        array('id_character' => '18','id_film' => '5'),
        array('id_character' => '18','id_film' => '6'),
        array('id_character' => '19','id_film' => '4'),
        array('id_character' => '20','id_film' => '1'),
        array('id_character' => '20','id_film' => '2'),
        array('id_character' => '20','id_film' => '3'),
        array('id_character' => '20','id_film' => '5'),
        array('id_character' => '20','id_film' => '6'),
        array('id_character' => '21','id_film' => '1'),
        array('id_character' => '21','id_film' => '2'),
        array('id_character' => '21','id_film' => '3'),
        array('id_character' => '21','id_film' => '5'),
        array('id_character' => '21','id_film' => '6'),
        array('id_character' => '22','id_film' => '2'),
        array('id_character' => '22','id_film' => '5'),
        array('id_character' => '22','id_film' => '6'),
        array('id_character' => '23','id_film' => '5'),
        array('id_character' => '24','id_film' => '5'),
        array('id_character' => '25','id_film' => '5'),
        array('id_character' => '25','id_film' => '6'),
        array('id_character' => '26','id_film' => '5'),
        array('id_character' => '27','id_film' => '6'),
        array('id_character' => '28','id_film' => '6'),
        array('id_character' => '29','id_film' => '6'),
        array('id_character' => '30','id_film' => '6'),
        array('id_character' => '31','id_film' => '6'),
        array('id_character' => '32','id_film' => '1'),
        array('id_character' => '33','id_film' => '1'),
        array('id_character' => '33','id_film' => '2'),
        array('id_character' => '33','id_film' => '3'),
        array('id_character' => '34','id_film' => '1'),
        array('id_character' => '35','id_film' => '1'),
        array('id_character' => '35','id_film' => '2'),
        array('id_character' => '36','id_film' => '1'),
        array('id_character' => '36','id_film' => '2'),
        array('id_character' => '36','id_film' => '3'),
        array('id_character' => '37','id_film' => '1'),
        array('id_character' => '38','id_film' => '1'),
        array('id_character' => '39','id_film' => '1'),
        array('id_character' => '40','id_film' => '1'),
        array('id_character' => '40','id_film' => '2'),
        array('id_character' => '41','id_film' => '1'),
        array('id_character' => '42','id_film' => '1'),
        array('id_character' => '43','id_film' => '1'),
        array('id_character' => '43','id_film' => '2'),
        array('id_character' => '44','id_film' => '1'),
        array('id_character' => '45','id_film' => '6'),
        array('id_character' => '46','id_film' => '1'),
        array('id_character' => '46','id_film' => '2'),
        array('id_character' => '46','id_film' => '3'),
        array('id_character' => '47','id_film' => '1'),
        array('id_character' => '48','id_film' => '1'),
        array('id_character' => '49','id_film' => '1'),
        array('id_character' => '50','id_film' => '1'),
        array('id_character' => '51','id_film' => '1'),
        array('id_character' => '51','id_film' => '2'),
        array('id_character' => '51','id_film' => '3'),
        array('id_character' => '52','id_film' => '1'),
        array('id_character' => '52','id_film' => '2'),
        array('id_character' => '52','id_film' => '3'),
        array('id_character' => '53','id_film' => '1'),
        array('id_character' => '53','id_film' => '2'),
        array('id_character' => '53','id_film' => '3'),
        array('id_character' => '54','id_film' => '1'),
        array('id_character' => '54','id_film' => '3'),
        array('id_character' => '55','id_film' => '1'),
        array('id_character' => '55','id_film' => '3'),
        array('id_character' => '56','id_film' => '1'),
        array('id_character' => '56','id_film' => '3'),
        array('id_character' => '57','id_film' => '1'),
        array('id_character' => '58','id_film' => '1'),
        array('id_character' => '58','id_film' => '2'),
        array('id_character' => '58','id_film' => '3'),
        array('id_character' => '59','id_film' => '1'),
        array('id_character' => '59','id_film' => '2'),
        array('id_character' => '60','id_film' => '2'),
        array('id_character' => '61','id_film' => '2'),
        array('id_character' => '62','id_film' => '2'),
        array('id_character' => '63','id_film' => '2'),
        array('id_character' => '63','id_film' => '3'),
        array('id_character' => '64','id_film' => '2'),
        array('id_character' => '64','id_film' => '3'),
        array('id_character' => '65','id_film' => '2'),
        array('id_character' => '66','id_film' => '2'),
        array('id_character' => '67','id_film' => '2'),
        array('id_character' => '67','id_film' => '3'),
        array('id_character' => '68','id_film' => '2'),
        array('id_character' => '68','id_film' => '3'),
        array('id_character' => '69','id_film' => '2'),
        array('id_character' => '70','id_film' => '2'),
        array('id_character' => '71','id_film' => '2'),
        array('id_character' => '72','id_film' => '2'),
        array('id_character' => '73','id_film' => '2'),
        array('id_character' => '74','id_film' => '2'),
        array('id_character' => '75','id_film' => '2'),
        array('id_character' => '76','id_film' => '2'),
        array('id_character' => '76','id_film' => '3'),
        array('id_character' => '77','id_film' => '2'),
        array('id_character' => '78','id_film' => '2'),
        array('id_character' => '78','id_film' => '3'),
        array('id_character' => '79','id_film' => '3'),
        array('id_character' => '80','id_film' => '3'),
        array('id_character' => '81','id_film' => '3'),
        array('id_character' => '81','id_film' => '4'),
        array('id_character' => '82','id_film' => '2'),
        array('id_character' => '82','id_film' => '3'),
        array('id_character' => '83','id_film' => '3'),
        array('id_character' => '89','id_film' => '4'),
        array('id_character' => '90','id_film' => '4'),
        array('id_character' => '91','id_film' => '5'),
        array('id_character' => '92','id_film' => '5'),
        array('id_character' => '93','id_film' => '5'),
        array('id_character' => '93','id_film' => '6'),
        array('id_character' => '94','id_film' => '5'),
        array('id_character' => '95','id_film' => '6'),
        array('id_character' => '96','id_film' => '5')
      );
}
